custom_tags:
    abbreviation:
        template: '@ezdesign/fields/ezrichtext/custom_tags/abbreviation.html.twig'
        icon: '/bundles/ezplatformadminui/img/ez-icons.svg#about'
        is_inline: true
        attributes:
            style:
                type: 'string'